name: Read

options:
  fileTypes:
    "icon":
      file: true 
  groupOrdering:
    - order: [ Read, ReadTests, Packages, Products ]

settings:
  base:
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    CODE_SIGN_IDENTITY: Apple Development
    CODE_SIGN_STYLE: Automatic
    DEAD_CODE_STRIPPING: YES
    DEVELOPMENT_TEAM: A3UXBEBE8Z
    ENABLE_APP_SANDBOX: YES
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    LOCALIZATION_PREFERS_STRING_CATALOGS: YES
    PRODUCT_NAME: Read
    STRING_CATALOG_GENERATE_SYMBOLS: YES
    SWIFT_VERSION: 6.2
    SWIFT_EMIT_LOC_STRINGS: YES
    SWIFT_STRICT_CONCURRENCY: YES
    # the following are replaced in the target Info.plists by a post
    # build script. They are needed (?) to build the plist that the
    # script then modifies.
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0
  configs:
    debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG $(inherited)
    release:
      VALIDATE_PRODUCT:  YES

targets:
  Read:
    type: application
    platform: iOS
    deploymentTarget: 26.0
    dependencies:
      - package: UDF
    sources:
      - Read
    entitlements:
      path: Read/Supporting Files/Read.entitlements
      properties:
        aps-environment: development
        com.apple.developer.icloud-container-identifiers:
          - iCloud.org.snafu.Read
        com.apple.developer.icloud-services:
          - CloudKit
    info:
      path: Read/Supporting Files/Info.plist
      properties:
        CFBundleDisplayName: $(TARGET_NAME)
        NSHumanReadableCopyright: Copyright 2025 Marco S Hyman
        UIApplicationSceneManifest_Generation: YES
        UIApplicationSupportsIndirectInputEvents: YES
        UIBackgroundModes: remote-notification
        UILaunchScreen_Generation: YES
        UISupportedInterfaceOrientations_iPad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations_iPhone:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIBackgroundModes:
          - remote-notification
    settings:
      base:
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: NO
        PRODUCT_BUNDLE_IDENTIFIER: org.snafu.Read
    postBuildScripts:
      - path: .buildversion.sh
        name: Build Version
        showEnvVars: NO
        basedOnDependencyAnalysis: NO
      - path: .swiftlint.sh
        name: Swift Lint
        showEnvVars: NO
        basedOnDependencyAnalysis: NO

  ReadTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 26.0
    dependencies:
      - target: Read
    sources:
      - ReadTests
    settings:
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_NAME: $(TARGET_NAME)
      PRODUCT_BUNDLE_IDENTIFIER: org.snafu.ReadTests
    schemes: none
 
packages:
  UDF:
    path: UDF

schemes:
  Read:
    build:
      targets:
        Read: all
    run:
      config: Debug
    test:
      config: Debug
      commandLineArguments:
        "-MEMORY": true
      gatherCoverageData: YES
      targets:
        - ReadTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      revealArchiveInOrganizer: YES
