include:
 - Config/templates.yml

name: Read

attributes:
  ORGANIZATIONNAME: "snafu"

options:
  bundleIdPrefix: org.snafu
  deploymentTarget:
    iOS: 17.0

settings:
  ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS : YES
  DEVELOPMENT_TEAM : A3UXBEBE8Z
  IPHONEOS_DEPLOYMENT_TARGET : 17.0
  LOCALIZATION_PREFERS_STRING_CATALOGS : YES
  ENABLE_USER_SCRIPT_SANDBOXING : NO
  SWIFT_STRICT_CONCURRENCY : complete
  SWIFT_VERSION : 6.1

schemes:
  Read:
    templates:
      - App

targets:
  Read:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - Read
    info:
      path: Read/Gen/Info.plist
      properties:
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest: 
          UIApplicationSupportsMultipleScenes: YES
          UISceneConfigurations: []
        UILaunchScreen:
          UILauchScreen: []
        UIBackgroundModes:
          - remote-notification
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    entitlements:
      path: Read/Gen/Read.entitlements
      properties:
        aps-environment: development
        com.apple.developer.icloud-container-identifiers:
          - iCloud.org.snafu.Read
        com.apple.developer.icloud-services:
          - CloudKit
    postBuildScripts:
      - path: Config/buildversion
        name: Build Version
        showEnvVars: NO
        basedOnDependencyAnalysis: NO
      - path: Config/swiftlint
        name: Swift Lint
        showEnvVars: NO
        basedOnDependencyAnalysis: NO
