name: Read
attributes:
  ORGANIZATIONNAME: "snafu"
options:
  bundleIdPrefix: org.snafu
  deploymentTarget:
    iOS: 17.0
configs:
  Debug: debug
  Release: release
schemes:
  App Develop:
    build:
      targets:
        Read: all
    run:
      config: Debug
    test:
      config: Debug
      commandLineArguments:
        -DDEBUG=1
      gatherCoverageData: True
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      revealArchiveInOrganizer: true
settings:
  ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS : YES
  DEVELOPMENT_TEAM : A3UXBEBE8Z
  IPHONEOS_DEPLOYMENT_TARGET : 17.0
  LOCALIZATION_PREFERS_STRING_CATALOGS : YES
  ENABLE_USER_SCRIPT_SANDBOXING : NO
  SWIFT_STRICT_CONCURRENCY : complete
  SWIFT_VERSION : 6.1
targets:
  Read:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - Read
    info:
      path: Read/Info.plist
      properties:
        UIBackgroundModes:
          - remote-notification
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    entitlements:
      path: Read/Read.entitlements
      properties:
        aps-environment: development
        com.apple.developer.icloud-container-identifiers:
          - iCloud.org.snafu.Read
        com.apple.developer.icloud-services:
          - CloudKit
    preBuildScripts:
      - path: Config/buildversion
        name: Build Version
        inputFiles:
          - $(SRCROOT)/plist.info
        outputFiles:
          - $(DERIVED_FILE_DIR)/plist.info
    postCompileScripts:
      - path: Config/swiftlint
        name: Swift Lint
