schemeTemplates:
  App:
    build:
      targets:
        ${scheme_name}: build
    run:
      config: Debug
    test:
      config: Debug
      commandLineArguments:
        -DDEBUG=1
      gatherCoverageData: True
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      revealArchiveInOrganizer: true


